# Generated by Django 4.2.7 on 2023-11-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fusion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileuploadapi",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
