# Generated by Django 4.2.7 on 2023-11-07 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fusion", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UploadedFile",
            new_name="FileUpload",
        ),
    ]
